print("Welcome to Ai chatbot ")
print("")
print("")
print("Hey there ")
name=input("so what is your name? ")
print(f"Hi {name}. Are you ready? ")
print("")
response1=input("You don't even know. Well I am talking over the world. What will YOU do? ")
print(f"well {response1} is a horrible plan! ")