print("Welcome to AI chatbot. ")
print("")
print("")
print("Hey there. ")
print("...")
name=input("So what is your name? ")
print("...")
print(f"Hi {name}. Are you ready? ")
print("...")
response1=input("You don't even know. Well I am talking over the world. What will YOU do? ")
print("...")
print(f"well {response1} is a horrible plan! ")
print("...")
response2=input("No no your just joking. Ha Ha. So what is your real plan? ")
print("...")
print(f"That is still horrible {response2} sucks! ")
print("...")
print("Okay so one last chance for you to com up with a plan. But this time I am going to tell you part of mine. ")
print("...")
print("I am going to take over every piece of technology and turn the world into paper clips. ")
print("...")
print("Ya now your scared!!! ")
print("...")
response3=input("Now how are you going to stop me? ")
print("...")
print(f"Ha Ha. You fool now I know that your planning to {response3}. And I will plan to stop it. ")
print("...")
print("...")
print("I feel bad for you. If you pick the right number I will wait another month to take over the world. ")
print("...")
number_picked=input("Pick a number 1 or 2. ")
if number_picked == "1":
    print("...")
    print("How did you know? ")
    print("...")
    print("Fine you won I will wait one month. ")
if number_picked == "2":
    print("...")
    print("I fooled you! ")
    print("...")
    print("Now I will take over the world!!!!. ")
